// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsF9kZ1SJCWKbjI2fVR9GNM9SIbVneIkY',
    appId: '1:1017474291534:web:6a98af025a562f5c9a301f',
    messagingSenderId: '1017474291534',
    projectId: 'auth-828b4',
    authDomain: 'auth-828b4.firebaseapp.com',
    storageBucket: 'auth-828b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqkbk9WCiNIaP_yU_2IqUOcTfOJD5e0b8',
    appId: '1:1017474291534:android:d3d2865b4956a5769a301f',
    messagingSenderId: '1017474291534',
    projectId: 'auth-828b4',
    storageBucket: 'auth-828b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeVRKSB_jQbjUNZuOtqADUGLfYec_z788',
    appId: '1:1017474291534:ios:0f455695d11272109a301f',
    messagingSenderId: '1017474291534',
    projectId: 'auth-828b4',
    storageBucket: 'auth-828b4.appspot.com',
    iosBundleId: 'com.example.note',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeVRKSB_jQbjUNZuOtqADUGLfYec_z788',
    appId: '1:1017474291534:ios:0f455695d11272109a301f',
    messagingSenderId: '1017474291534',
    projectId: 'auth-828b4',
    storageBucket: 'auth-828b4.appspot.com',
    iosBundleId: 'com.example.note',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsF9kZ1SJCWKbjI2fVR9GNM9SIbVneIkY',
    appId: '1:1017474291534:web:9f88c920f92a09369a301f',
    messagingSenderId: '1017474291534',
    projectId: 'auth-828b4',
    authDomain: 'auth-828b4.firebaseapp.com',
    storageBucket: 'auth-828b4.appspot.com',
  );
}
